let chartTrend=null,currentClass=null,currentMember=null;
const $=id=>document.getElementById(id); const D=()=>window.DB.get(); const E=()=>window.Engine;
const views=['overview','classes','class-detail','members','member-profile','input-violation','input-sdb','transactions','achievements','events','duty','workflow','rules','admin','audit'];
const nav=[['overview','Tổng quan & Xếp hạng','ph-chart-line'],['classes','Lớp học','ph-buildings'],['members','Đoàn viên','ph-users-three'],['input-violation','Ghi nhận vi phạm','ph-warning'],['input-sdb','Sổ đầu bài','ph-notebook'],['transactions','Giao dịch điểm','ph-arrows-left-right'],['achievements','Thành tích','ph-medal'],['events','Sự kiện','ph-calendar-blank'],['duty','Trực tuần','ph-calendar-check'],['workflow','Duyệt & Khiếu nại','ph-check-square'],['rules','Rule Engine','ph-git-branch'],['admin','Quản trị dữ liệu','ph-shield-check'],['audit','Audit Log','ph-list-dashes']];
function switchView(id){views.forEach(v=>{const x=$('view-'+v);if(x)x.classList.toggle('active',v===id);});document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));render(id);}
function renderNav(){const canAdmin=E().currentUser.role==='SUPER_ADMIN'||E().currentUser.role==='ADMIN';$('main-nav').innerHTML=nav.filter(x=>canAdmin||!['rules','admin','audit'].includes(x[0])).map(x=>`<button data-nav="${x[0]}" onclick="switchView('${x[0]}')" class="sidebar-item w-full text-left px-4 py-2.5 rounded-lg flex items-center gap-3 text-sm text-slate-600"><i class="ph ${x[2]} text-lg"></i>${x[1]}</button>`).join('');}
function context(){const d=D();$('headerYear').innerHTML=d.years.map(y=>`<option value="${y.id}">${y.name}</option>`).join('');$('headerYear').value=E().currentYearId;$('headerWeek').innerHTML=Array.from({length:35},(_,i)=>`<option value="${i+1}">Tuần ${i+1}</option>`).join('');$('headerWeek').value=E().currentWeek;$('roleSwitcher').value=E().currentUser.role;$('current-user-name').textContent=E().currentUser.name;$('current-role-badge').textContent=E().currentUser.role;}
function render(id){const f={overview:renderOverview,classes:renderClasses,'class-detail':renderClassDetail,members:renderMembers,'member-profile':renderMemberProfile,'input-violation':setupViolation,'input-sdb':setupSdb,transactions:renderTransactions,achievements:renderAchievements,events:renderEvents,duty:renderDuty,fees:renderFees,workflow:renderWorkflow,rules:renderRules,admin:renderAdmin,audit:renderAudit};if(f[id])f[id]();renderNotifications();}
function renderOverview(){const d=D(),rows=E().leaderboard($('dashGrade')?.value||'ALL'),avg=rows.length?rows.reduce((a,x)=>a+x.total,0)/rows.length:0,viol=d.violations.filter(v=>v.week===E().currentWeek),bonus=d.transactions.filter(t=>t.week===E().currentWeek&&d.rules.find(r=>r.id===t.ruleId)?.points>0),leader=rows[0];$('kpis').innerHTML=[['Lớp',rows.length,'blue'],['Đoàn viên',d.members.length,'purple'],['Điểm TB',avg.toFixed(1),'green'],['Vi phạm tuần',viol.length,'red'],['Điểm cộng',bonus.reduce((a,t)=>a+(d.rules.find(r=>r.id===t.ruleId)?.points||0),0),'amber']].map(k=>`<div class="card p-5"><div class="text-sm text-slate-500">${k[0]}</div><div class="text-2xl font-extrabold mt-1">${k[1]}</div></div>`).join('');$('leader-card').innerHTML=leader?`<div class="text-sm text-slate-500">Lớp dẫn đầu tuần ${E().currentWeek}</div><div class="text-3xl font-black mt-1">${leader.classInfo.name}</div><div class="text-blue-600 font-bold mt-1">${leader.total} điểm · #1</div>`:'';$('rank-body').innerHTML=rows.slice(0,10).map(r=>`<tr onclick="openClass('${r.classInfo.id}')" class="row-click"><td class="font-black">#${r.rank}</td><td class="font-bold">${r.classInfo.name}</td><td>${r.breakdown.discipline}</td><td>${r.breakdown.study}</td><td class="text-emerald-600">+${r.breakdown.bonus}</td><td class="font-black">${r.total}</td><td>${r.rank<=3?UI.badge('Top','green'):''}</td></tr>`).join('');drawTrend();}
function drawTrend(){const c=$('trendChart');if(!c)return;const rows=E().leaderboard();const top=rows.slice(0,5);if(chartTrend)chartTrend.destroy();chartTrend=new Chart(c,{type:'line',data:{labels:Array.from({length:35},(_,i)=>`T${i+1}`),datasets:top.map((r,i)=>({label:r.classInfo.name,data:Array.from({length:35},(_,w)=>E().calculate(r.classInfo.id,w+1)?.total||0),tension:.3}))},options:{responsive:true,plugins:{legend:{position:'bottom'}},scales:{y:{beginAtZero:false}}}});}
function renderClasses(){const d=D();$('class-grid').innerHTML=d.classes.map(c=>{const s=E().calculate(c.id);const rank=E().leaderboard().find(x=>x.classInfo.id===c.id)?.rank;return `<button onclick="openClass('${c.id}')" class="card p-5 text-left hover:border-blue-300 hover:shadow-md transition"><div class="flex justify-between"><div><div class="text-xs text-slate-400">Khối ${c.grade} · ${c.cohort}</div><div class="text-xl font-black mt-1">${c.name}</div></div><div class="text-blue-600 font-black">#${rank||'-'}</div></div><div class="grid grid-cols-3 gap-2 mt-5 text-center"><div class="metric"><b>${s.breakdown.discipline}</b><span>Nề nếp</span></div><div class="metric"><b>${s.breakdown.study}</b><span>Học tập</span></div><div class="metric"><b>+${s.breakdown.bonus}</b><span>Bonus</span></div></div></button>`}).join('');}
function openClass(id){currentClass=id;switchView('class-detail');}
function renderClassDetail(){if(!currentClass)return;const d=D(),c=d.classes.find(x=>x.id===currentClass),s=E().calculate(currentClass),mem=d.members.filter(m=>m.classId===currentClass),sec=mem.find(m=>m.role==='Bí thư Chi đoàn'),duty=d.duties.find(x=>x.week===E().currentWeek&&x.classId===currentClass),hist=E().rankHistory(currentClass),viol=d.violations.filter(v=>v.classId===currentClass&&v.week===E().currentWeek),ach=d.achievements.filter(a=>a.classId===currentClass&&a.week===E().currentWeek);$('class-title').textContent=c.name;$('class-sub').textContent=`Khối ${c.grade} · ${c.cohort} · ${mem.length} Đoàn viên`;$('class-meta').innerHTML=`Bí thư: <b>${sec?.name||'—'}</b> · Cán bộ tổng hợp tuần: <b>${duty?.memberId?d.members.find(m=>m.id===duty.memberId)?.name:'—'}</b>`;$('class-total').textContent=s.total;$('score-breakdown').innerHTML=[['Nề nếp',s.breakdown.discipline,s.breakdown.transDiscipline],['Học tập',s.breakdown.study,s.breakdown.transStudy],['Điểm cộng',s.breakdown.bonus,s.breakdown.transBonus]].map(([name,val,arr])=>`<div class="p-4 rounded-xl bg-slate-50"><div class="flex justify-between"><b>${name}</b><b>${name==='Điểm cộng'?'+':''}${val}</b></div><div class="mt-3 space-y-2">${arr.length?arr.map(t=>`<div class="flex justify-between text-sm"><span>${t.ruleName}</span><b class="${t.points>0?'text-emerald-600':'text-red-600'}">${t.points>0?'+':''}${t.points}</b></div>`).join(''):'<div class="text-xs text-slate-400">Không có giao dịch</div>'}</div></div>`).join('');$('class-violations').innerHTML=viol.length?viol.map(v=>{const m=d.members.find(x=>x.id===v.memberId);const r=d.rules.find(x=>x.id===v.ruleId);return `<tr><td>${v.week}</td><td>${m?.name||'Tập thể'}</td><td>${r?.name}</td><td class="text-red-600 font-bold">${r?.points}</td><td>${v.status}</td></tr>`}).join(''):'<tr><td colspan="5" class="empty">Không có vi phạm tuần này</td></tr>';$('class-achievements').innerHTML=ach.length?ach.map(a=>`<tr><td>${a.title}</td><td>${a.rank}</td><td class="text-emerald-600 font-bold">+${a.points}</td></tr>`).join(''):'<tr><td colspan="3" class="empty">Chưa có thành tích</td></tr>';$('member-mini').innerHTML=mem.slice(0,8).map(m=>`<button onclick="openMember('${m.id}')" class="text-left p-3 border rounded-lg hover:border-blue-300"><b>${m.name}</b><div class="text-xs text-slate-400">${m.role}</div></button>`).join('');$('rank-history').innerHTML=hist.slice(-10).reverse().map((x,i)=>`<tr><td>Tuần ${x.week}</td><td>${x.total}</td><td>#${x.rank}</td><td>${i<hist.length-1?(hist[hist.length-2-i]?.rank-x.rank>0?'↑':'↓'):''}</td></tr>`).join('');}
function renderMembers(){const d=D(),g=$('memberGrade').value||'ALL',c=$('memberClass').value||'ALL',q=($('memberSearch').value||'').toLowerCase();$('memberClass').innerHTML='<option value="ALL">Tất cả lớp</option>'+d.classes.filter(x=>g==='ALL'||x.grade==g).map(x=>`<option value="${x.id}">${x.name}</option>`).join('');$('memberClass').value=c==='ALL'?'ALL':c;const list=d.members.filter(m=>(g==='ALL'||d.classes.find(c=>c.id===m.classId)?.grade==g)&&(c==='ALL'||m.classId===c)&&m.name.toLowerCase().includes(q));$('member-body').innerHTML=list.slice(0,250).map(m=>{const cl=d.classes.find(c=>c.id===m.classId);const count=d.violations.filter(v=>v.memberId===m.id).length;return `<tr class="row-click" onclick="openMember('${m.id}')"><td>${m.code}</td><td class="font-bold">${m.name}</td><td>${cl?.name}</td><td>${m.role}</td><td>${count}</td><td>${m.dues.hki&&m.dues.hkii?UI.badge('Đủ','green'):UI.badge('Thiếu','amber')}</td></tr>`}).join('');}
function openMember(id){currentMember=id;switchView('member-profile');}
function renderMemberProfile(){if(!currentMember)return;const d=D(),m=d.members.find(x=>x.id===currentMember),c=d.classes.find(x=>x.id===m.classId),vs=d.violations.filter(v=>v.memberId===m.id),as=d.achievements.filter(a=>a.memberId===m.id),impact=vs.reduce((sum,v)=>sum+(d.rules.find(r=>r.id===v.ruleId)?.points||0),0);$('member-name').textContent=m.name;$('member-sub').textContent=`${c.name} · ${m.role} · ${m.code}`;$('member-info').innerHTML=`Ngày sinh: ${m.dob} · ${m.gender} · Ngày vào Đoàn: ${m.joinDate}`;$('member-stats').innerHTML=`<div><b>${vs.length}</b><span>Vi phạm</span></div><div><b>${impact}</b><span>Điểm ảnh hưởng lớp</span></div><div><b>${as.length}</b><span>Thành tích</span></div>`;$('member-violations').innerHTML=vs.slice().reverse().map(v=>{const r=d.rules.find(x=>x.id===v.ruleId);return `<tr><td>Tuần ${v.week}</td><td>${r?.name}</td><td>${r?.category}</td><td class="text-red-600 font-bold">${r?.points}</td></tr>`}).join('')||'<tr><td colspan="4" class="empty">Không có dữ liệu</td></tr>';$('member-achievements').innerHTML=as.slice().reverse().map(a=>`<tr><td>Tuần ${a.week}</td><td>${a.title}</td><td>${a.rank}</td><td class="text-emerald-600 font-bold">+${a.points}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Chưa có thành tích</td></tr>';}
function setupViolation(){const d=D();fillSelect('vioClass',d.classes.map(c=>[c.id,c.name]));fillSelect('vioRule',d.rules.filter(r=>r.points<0).map(r=>[r.id,`${r.name} (${r.points})`]));$('vioClass').onchange=()=>fillSelect('vioMember',[['','Tập thể'],...d.members.filter(m=>m.classId===$('vioClass').value).map(m=>[m.id,m.name])]);$('vioMember').onchange=()=>{};}
function setupSdb(){const d=D();fillSelect('sdbClass',d.classes.map(c=>[c.id,c.name]));fillSelect('sdbRule',d.rules.filter(r=>r.type==='STUDY').map(r=>[r.id,`${r.name} (${r.points})`]));}
function fillSelect(id,items){$(id).innerHTML='<option value="">-- Chọn --</option>'+items.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('');}
function submitRecord(type){const d=D(),classId=$(type==='violation'?'vioClass':'sdbClass').value,ruleId=$(type==='violation'?'vioRule':'sdbRule').value,memberId=$(type==='violation'?'vioMember':'sdbMember')?.value||null,note=$(type==='violation'?'vioNote':'sdbNote').value;if(!classId||!ruleId)return UI.toast('Hãy chọn đủ lớp và luật','warning');const rule=d.rules.find(r=>r.id===ruleId);window.DB.addTransaction({yearId:E().currentYearId,week:E().currentWeek,classId,memberId:memberId||null,ruleId,note,status:E().can('APPROVE')?'APPROVED':'PENDING',sourceType:type.toUpperCase()},E().currentUser);UI.toast('Đã ghi nhận giao dịch điểm');$(type==='violation'?'violationForm':'sdbForm').reset();}
function renderTransactions(){const d=D(),list=d.transactions.filter(t=>t.yearId===E().currentYearId&&t.week===E().currentWeek);$('transaction-body').innerHTML=list.slice().reverse().slice(0,150).map(t=>{const c=d.classes.find(x=>x.id===t.classId),r=d.rules.find(x=>x.id===t.ruleId),m=t.memberId?d.members.find(x=>x.id===t.memberId):null;return `<tr><td>${c?.name}</td><td>${m?.name||'Tập thể'}</td><td>${r?.name}</td><td class="${r?.points>0?'text-emerald-600':'text-red-600'} font-bold">${r?.points>0?'+':''}${r?.points}</td><td>${UI.badge(t.status,t.status==='APPROVED'?'green':t.status==='PENDING'?'amber':'red')}</td><td>${t.sourceType||'—'}</td></tr>`}).join('');}
function renderAchievements(){const d=D();$('achievement-body').innerHTML=d.achievements.slice().reverse().map(a=>{const c=d.classes.find(x=>x.id===a.classId),m=a.memberId?d.members.find(x=>x.id===a.memberId):null;return `<tr><td>Tuần ${a.week}</td><td class="font-bold">${a.title}</td><td>${c?.name}</td><td>${m?.name||'Tập thể'}</td><td>${a.rank}</td><td class="text-emerald-600 font-bold">+${a.points}</td></tr>`}).join('');}
function renderEvents(){const d=D();$('event-grid').innerHTML=d.events.map(e=>`<div class="card p-5"><div class="flex justify-between">${UI.badge(e.type,'blue')}<span class="text-xs text-slate-400">${e.date}</span></div><h3 class="font-black text-lg mt-3">${e.name}</h3><p class="text-sm text-slate-500 mt-1">${e.location} · ${e.participants} người tham gia</p><p class="text-xs text-slate-400 mt-3">${e.description}</p></div>`).join('');}
function renderFees(){const d=D();$('fee-body').innerHTML=d.members.slice(0,300).map(m=>{const c=d.classes.find(c=>c.id===m.classId);return `<tr><td>${m.code}</td><td class="font-bold">${m.name}</td><td>${c?.name}</td><td>${m.dues.hki?UI.badge('Đã đóng','green'):UI.badge('Chưa','amber')}</td><td>${m.dues.hkii?UI.badge('Đã đóng','green'):UI.badge('Chưa','amber')}</td><td><button class="btn-small green" onclick="toggleFee('${m.id}','hki')">Đổi HKI</button> <button class="btn-small" onclick="toggleFee('${m.id}','hkii')">Đổi HKII</button></td></tr>`}).join('');}
function toggleFee(id,term){window.DB.toggleDues(id,term,E().currentUser);renderFees();}
function openSimulation(){if(!currentClass)return UI.toast('Hãy mở một lớp trước','warning');const d=D();$('simRule').innerHTML=d.rules.map(r=>`<option value="${r.id}">${r.name} (${r.points>0?'+':''}${r.points})</option>`).join('');updateSimulation();$('simulationModal').classList.remove('hidden');$('simulationModal').classList.add('flex');$('simRule').onchange=updateSimulation;}
function updateSimulation(){if(!currentClass)return;const old=E().calculate(currentClass).total,r=D().rules.find(x=>x.id===$('simRule').value);$('simOld').textContent=old;$('simNew').textContent=old+(r?.points||0);}
function closeSimulation(){$('simulationModal').classList.add('hidden');$('simulationModal').classList.remove('flex');}
function applySimulation(){const r=D().rules.find(x=>x.id===$('simRule').value);if(!r)return;window.DB.addTransaction({yearId:E().currentYearId,week:E().currentWeek,classId:currentClass,memberId:null,ruleId:r.id,note:'Áp dụng từ Score Simulation',status:E().can('APPROVE')?'APPROVED':'PENDING',sourceType:'SIMULATION'},E().currentUser);closeSimulation();UI.toast('Đã tạo transaction từ mô phỏng');renderClassDetail();}
function exportData(){const blob=new Blob([JSON.stringify(D(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ctn-score-demo.json';a.click();URL.revokeObjectURL(a.href);}
function renderDuty(){const d=D();$('duty-body').innerHTML=d.duties.filter(x=>x.week===E().currentWeek).map(x=>{const c=d.classes.find(c=>c.id===x.classId),m=d.members.find(m=>m.id===x.memberId);return `<tr><td>Tuần ${x.week}</td><td class="font-bold">${c?.name}</td><td>${m?.name}</td><td>${UI.badge(x.status,x.status==='ĐÃ CHỐT'?'green':'amber')}</td></tr>`}).join('');}
function renderWorkflow(){const d=D(),p=d.transactions.filter(t=>t.status==='PENDING');$('pending-body').innerHTML=p.map(t=>{const c=d.classes.find(x=>x.id===t.classId),r=d.rules.find(x=>x.id===t.ruleId);return `<tr><td>${c?.name}</td><td>${r?.name}</td><td>${r?.points}</td><td><button onclick="approve('${t.id}')" class="btn-small green">Duyệt</button></td></tr>`}).join('')||'<tr><td colspan="4" class="empty">Không có giao dịch chờ duyệt</td></tr>';$('appeal-box').innerHTML=d.appeals.length?d.appeals.map(a=>`<div class="p-3 border rounded-lg">${a.reason}</div>`).join(''):'<div class="empty">Chưa có khiếu nại</div>';}
function approve(id){window.DB.setTransactionStatus(id,'APPROVED',E().currentUser);UI.toast('Đã duyệt');renderWorkflow();}
function renderRules(){const d=D();$('rule-body').innerHTML=d.rules.map(r=>`<tr><td class="font-mono">${r.code}<div class="text-xs text-slate-400">v${r.version}</div></td><td class="font-bold">${r.name}<div class="text-xs text-slate-400">${r.category} · ${r.source}</div></td><td>${r.calcType}</td><td class="${r.points>0?'text-emerald-600':'text-red-600'} font-black">${r.points>0?'+':''}${r.points}</td><td>${r.scope}</td><td>${r.active?UI.badge('Active','green'):UI.badge('Off')}</td></tr>`).join('');}
function addRule(){const name=prompt('Tên luật');if(!name)return;const pts=Number(prompt('Điểm, ví dụ -5 hoặc 10'));if(!Number.isFinite(pts))return;window.DB.addRule({code:'CUSTOM_'+Date.now(),type:pts>0?'BONUS':'DISCIPLINE',category:'Tùy chỉnh',name,points:pts,calcType:'FIXED',scope:'CLASS',source:'DEMO'},E().currentUser);UI.toast('Đã thêm luật');renderRules();}
function renderAdmin(){const r=window.DB.integrity();$('integrity').innerHTML=`<b>${r.errors.length?'⚠ Có lỗi':'✓ Hệ thống hợp lệ'}</b><div class="text-xs mt-2">${r.totalClasses}/39 lớp · ${r.totalMembers} đoàn viên · ${r.totalTransactions} giao dịch · ${r.totalWeeks}/35 tuần</div>${r.errors.slice(0,10).map(x=>`<div class="text-xs text-red-600">${x}</div>`).join('')}`;}
function renderAudit(){const d=D();$('audit-body').innerHTML=d.audit_logs.slice().reverse().slice(0,100).map(x=>`<tr><td>${new Date(x.timestamp).toLocaleString('vi-VN')}</td><td>${x.user}</td><td>${x.role}</td><td>${x.action}</td><td>${x.details}</td></tr>`).join('');}
function renderNotifications(){const d=D();const n=d.notifications||[];$('notif-count').textContent=n.length;}
function globalSearch(){const q=$('globalSearch').value.toLowerCase().trim();if(!q){$('searchResults').classList.add('hidden');return;}const d=D(),ms=d.members.filter(m=>m.name.toLowerCase().includes(q)||m.code.toLowerCase().includes(q)).slice(0,5),cs=d.classes.filter(c=>c.name.toLowerCase().includes(q)).slice(0,5);$('searchResults').innerHTML=[...cs.map(c=>`<button onclick="openClass('${c.id}')" class="search-item"><b>${c.name}</b><span>Lớp</span></button>`),...ms.map(m=>`<button onclick="openMember('${m.id}')" class="search-item"><b>${m.name}</b><span>${d.classes.find(c=>c.id===m.classId)?.name}</span></button>`)].join('')||'<div class="p-4 text-sm text-slate-400">Không tìm thấy</div>';$('searchResults').classList.remove('hidden');}
function init(){context();renderNav();['headerWeek','headerYear','roleSwitcher'].forEach(id=>$(id).addEventListener('change',()=>{if(id==='headerWeek')E().currentWeek=Number($(id).value);if(id==='headerYear')E().currentYearId=$(id).value;if(id==='roleSwitcher')E().setContext(E().currentYearId,E().currentWeek,$(id).value);context();renderNav();render('overview');}));$('dashGrade').addEventListener('change',renderOverview);$('memberGrade').addEventListener('change',renderMembers);$('memberClass').addEventListener('change',renderMembers);$('memberSearch').addEventListener('input',renderMembers);$('globalSearch').addEventListener('input',globalSearch);$('violationForm').addEventListener('submit',e=>{e.preventDefault();submitRecord('violation')});$('sdbForm').addEventListener('submit',e=>{e.preventDefault();submitRecord('sdb')});switchView('overview');}
window.switchView=switchView;window.openSimulation=openSimulation;window.closeSimulation=closeSimulation;window.applySimulation=applySimulation;window.exportData=exportData;window.toggleFee=toggleFee;window.openClass=openClass;window.openMember=openMember;window.approve=approve;window.addRule=addRule;window.runIntegrityCheck=renderAdmin;window.seedDemo=()=>{if(confirm('Khởi tạo lại toàn bộ dữ liệu demo?')){window.DB.seed();location.reload();}};window.resetDemo=()=>{if(confirm('Xóa toàn bộ dữ liệu local?'))window.DB.reset();};document.addEventListener('DOMContentLoaded',init);
