class ScoreEngine {
 constructor(db){this.db=db;this.currentYearId='Y2526';this.currentWeek=35;this.currentUser={name:'Quản trị hệ thống',role:'SUPER_ADMIN',scope:'ALL',classId:null};}
 setContext(year,week,role){this.currentYearId=year;this.currentWeek=Number(week);const map={SUPER_ADMIN:['Quản trị hệ thống','ALL',null],ADMIN:['Bí thư Đoàn trường','ALL',null],DUTY:['Cán bộ trực tuần','ALL',null],SECRETARY:['Bí thư 10 Tin','CLASS','C10_Tin']};const x=map[role]||map.SUPER_ADMIN;this.currentUser={name:x[0],role,scope:x[1],classId:x[2]};}
 can(p,c=null){const r=this.currentUser.role;if(r==='SUPER_ADMIN')return true;if(p==='VIEW_ALL')return r!=='SECRETARY';if(p==='MANAGE_RULES'||p==='APPROVE'||p==='MANAGE_YEAR'||p==='AUDIT')return r==='ADMIN';if(p==='CREATE_VIOLATION')return r!=='SECRETARY'||c===this.currentUser.classId;if(p==='EDIT_DUES')return r==='ADMIN'||(r==='SECRETARY'&&c===this.currentUser.classId);return false;}
 transactions(classId,week=this.currentWeek){return this.db.get().transactions.filter(t=>t.classId===classId&&t.yearId===this.currentYearId&&t.week===week&&t.status==='APPROVED');}
 calculate(classId,week=this.currentWeek){const d=this.db.get(),c=d.classes.find(x=>x.id===classId);if(!c)return null;const trans=this.transactions(classId,week);let b={discipline:d.settings.baseDiscipline,study:d.settings.baseStudy,bonus:0,transDiscipline:[],transStudy:[],transBonus:[]};for(const t of trans){const r=d.rules.find(x=>x.id===t.ruleId);if(!r)continue;const item={...t,ruleName:r.name,points:r.points,category:r.category};if(r.type==='DISCIPLINE'){b.discipline+=r.points;b.transDiscipline.push(item);}else if(r.type==='STUDY'){b.study+=r.points;b.transStudy.push(item);}else{b.bonus+=r.points;b.transBonus.push(item);}}b.discipline=Math.max(0,b.discipline);b.study=Math.max(0,b.study);return{classInfo:c,breakdown:b,total:b.discipline+b.study+b.bonus,transCount:trans.length};}
 leaderboard(grade='ALL',week=this.currentWeek){let cs=this.db.get().classes;if(this.currentUser.scope==='CLASS')cs=cs.filter(c=>c.id===this.currentUser.classId);if(grade!=='ALL')cs=cs.filter(c=>String(c.grade)===String(grade));const rows=cs.map(c=>this.calculate(c.id,week)).sort((a,b)=>b.total-a.total||b.breakdown.discipline-a.breakdown.discipline);return rows.map((x,i)=>({...x,rank:i+1}));}
 rankHistory(classId){const out=[];for(let w=1;w<=35;w++){const all=this.leaderboard('ALL',w),r=all.find(x=>x.classInfo.id===classId);if(r)out.push({week:w,total:r.total,rank:r.rank});}return out;}
 explain(classId,week=this.currentWeek){const x=this.calculate(classId,week);return x?[...x.breakdown.transDiscipline,...x.breakdown.transStudy,...x.breakdown.transBonus]:[];}
}
window.Engine=new ScoreEngine(window.DB);
